const http = require('node:http');
const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');

const PORT = Number(process.env.PORT || 3000);
const ROOT_DIRECTORY = __dirname;
const FRONTEND_DIRECTORY = path.resolve(ROOT_DIRECTORY, '..', 'frontend', 'dist');
const DATA_DIRECTORY = path.join(ROOT_DIRECTORY, 'data');
const LIEN_CHI_FILE = path.join(DATA_DIRECTORY, 'lien-chi.json');
const CLUBS_FILE = path.join(DATA_DIRECTORY, 'clubs.json');
const ADMIN_KEY = process.env.UET_ADMIN_KEY || 'uet-admin-2026';
const MAX_BODY_SIZE = 4_000_000;
const APP_ROUTES = new Set(['/', '/gioi-thieu', '/ban-do', '/lien-chi', '/cau-lac-bo']);
const MIME_TYPES = { '.css': 'text/css; charset=utf-8', '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.json': 'application/json; charset=utf-8', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.svg': 'image/svg+xml', '.webp': 'image/webp', '.glb': 'model/gltf-binary', '.gltf': 'model/gltf+json', '.bin': 'application/octet-stream' };
const CLUB_CATEGORIES = new Set(['academic', 'tech', 'art', 'sport', 'media', 'community']);

function sendJson(response, statusCode, payload) { response.writeHead(statusCode, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }); response.end(JSON.stringify(payload)); }
function sendError(response, statusCode, message) { sendJson(response, statusCode, { error: message }); }
function isAuthorized(request) { return request.headers['x-admin-key'] === ADMIN_KEY; }
async function readJson(filePath) { return JSON.parse(await fs.readFile(filePath, 'utf8')); }
async function writeJson(filePath, value) { const temporaryFile = `${filePath}.tmp`; await fs.writeFile(temporaryFile, `${JSON.stringify(value, null, 2)}\n`, 'utf8'); await fs.rename(temporaryFile, filePath); }
function normalizeText(value, field, maximum, required = false) { const text = typeof value === 'string' ? value.trim() : ''; if (required && !text) throw new Error(`${field} là bắt buộc.`); if (text.length > maximum) throw new Error(`${field} tối đa ${maximum} ký tự.`); return text; }
function normalizeColor(value, fallback) { const color = typeof value === 'string' ? value.trim() : ''; if (!color) return fallback; if (!/^#[0-9a-fA-F]{6}$/.test(color)) throw new Error('Màu sắc phải có định dạng #RRGGBB.'); return color.toLowerCase(); }
function normalizeLink(value) { const link = typeof value === 'string' ? value.trim() : ''; if (!link) return ''; try { return ['http:', 'https:'].includes(new URL(link).protocol) ? link : ''; } catch { return ''; } }
function normalizePublicLogo(value, directory) { const logoPath = typeof value === 'string' ? value.trim() : ''; return new RegExp(`^/assets/${directory}/[a-zA-Z0-9_-]+\\.(svg|png|webp|jpe?g)$`, 'i').test(logoPath) ? logoPath : ''; }
function normalizeParagraphs(value, label) { return (Array.isArray(value) ? value : []).map(item => ({ text: normalizeText(item?.text, label, 4000), isBullet: item?.isBullet === true })).filter(item => item.text); }
function normalizeLienChi(input, existing = {}, index = 0) { const source = input && typeof input === 'object' ? input : {}; const pick = field => typeof source[field] === 'string' ? source[field] : (existing[field] || ''); return { id: typeof source.id === 'string' && /^[a-z0-9-]+$/.test(source.id) ? source.id : (existing.id || `lien-chi-${index + 1}`), sortOrder: Number.isInteger(source.sortOrder) ? source.sortOrder : (existing.sortOrder || index + 1), name: normalizeText(pick('name'), 'Tên Liên chi', 160, true), shortName: normalizeText(pick('shortName'), 'Tên viết tắt', 80), monogram: normalizeText(pick('monogram'), 'Chữ lồng logo', 6), unitType: ['Khoa', 'Viện'].includes(pick('unitType')) ? pick('unitType') : 'Khoa', logoUrl: normalizePublicLogo(pick('logoUrl'), 'lien-chi'), accentColor: normalizeColor(pick('accentColor'), '#087ea4'), fanpageUrl: normalizeLink(pick('fanpageUrl')), summary: normalizeText(pick('summary') || pick('description'), 'Câu dẫn Liên chi', 400), paragraphs: normalizeParagraphs(source.paragraphs ?? existing.paragraphs, 'Đoạn giới thiệu Liên chi') }; }
function normalizeClub(input, index) { return { id: typeof input?.id === 'string' && /^[a-z0-9-]+$/.test(input.id) ? input.id : `clb-${index + 1}`, sortOrder: Number.isInteger(input?.sortOrder) ? input.sortOrder : index + 1, name: normalizeText(input?.name, 'Tên câu lạc bộ', 160, true), shortName: normalizeText(input?.shortName, 'Tên viết tắt', 80), monogram: normalizeText(input?.monogram, 'Chữ lồng logo', 6), logoUrl: normalizePublicLogo(input?.logoUrl, 'clubs'), accentColor: normalizeColor(input?.accentColor, '#087ea4'), category: CLUB_CATEGORIES.has(input?.category) ? input.category : 'community', governingBody: normalizeText(input?.governingBody, 'Đơn vị chủ quản', 200), fanpageUrl: normalizeLink(input?.fanpageUrl), summary: normalizeText(input?.summary, 'Câu dẫn', 400), paragraphs: normalizeParagraphs(input?.paragraphs, 'Đoạn giới thiệu câu lạc bộ') }; }
async function readLienChi() { const items = await readJson(LIEN_CHI_FILE); if (!Array.isArray(items)) throw new Error('Dữ liệu Liên chi không hợp lệ.'); return items.map(normalizeLienChi).sort((a, b) => a.sortOrder - b.sortOrder); }
async function readClubs() { const items = await readJson(CLUBS_FILE); if (!Array.isArray(items)) throw new Error('Dữ liệu câu lạc bộ không hợp lệ.'); return items.map(normalizeClub).sort((a, b) => a.sortOrder - b.sortOrder); }
function readRequestBody(request) { return new Promise((resolve, reject) => { let size = 0; let body = ''; request.setEncoding('utf8'); request.on('data', chunk => { size += Buffer.byteLength(chunk); if (size > MAX_BODY_SIZE) { reject(new Error('Dữ liệu gửi lên quá lớn.')); request.destroy(); return; } body += chunk; }); request.on('end', () => { try { resolve(body ? JSON.parse(body) : {}); } catch { reject(new Error('Dữ liệu JSON không hợp lệ.')); } }); request.on('error', reject); }); }
async function handleLienChiApi(request, response, url) { const id = url.pathname.match(/^\/api\/lien-chi\/([a-zA-Z0-9-]+)$/)?.[1]; if (request.method === 'GET' && url.pathname === '/api/lien-chi') return sendJson(response, 200, await readLienChi()); if (!isAuthorized(request)) return sendError(response, 401, 'Cần mật khẩu quản trị để thay đổi danh mục.'); const items = await readLienChi(); if (request.method === 'POST' && url.pathname === '/api/lien-chi') { const item = normalizeLienChi(await readRequestBody(request), { id: crypto.randomUUID(), sortOrder: items.length ? Math.max(...items.map(value => value.sortOrder)) + 1 : 1 }); items.push(item); await writeJson(LIEN_CHI_FILE, items); return sendJson(response, 201, item); } const index = items.findIndex(item => item.id === id); if (index < 0) return sendError(response, 404, 'Không tìm thấy Liên chi.'); if (request.method === 'PATCH') { items[index] = normalizeLienChi(await readRequestBody(request), items[index], index); await writeJson(LIEN_CHI_FILE, items); return sendJson(response, 200, items[index]); } if (request.method === 'DELETE') { items.splice(index, 1); await writeJson(LIEN_CHI_FILE, items); return sendJson(response, 200, { success: true }); } return sendError(response, 405, 'Phương thức hoặc đường dẫn API không được hỗ trợ.'); }
async function handleApi(request, response, url) { if (url.pathname.startsWith('/api/lien-chi')) return handleLienChiApi(request, response, url); if (request.method === 'GET' && url.pathname === '/api/clubs') return sendJson(response, 200, await readClubs()); return sendError(response, 404, 'Không tìm thấy API được yêu cầu.'); }
async function serveStaticFile(request, response, url) { const requestedPath = APP_ROUTES.has(url.pathname) ? 'index.html' : decodeURIComponent(url.pathname).replace(/^[/\\]+/, ''); const safePath = path.normalize(requestedPath).replace(/^[/\\]+/, ''); if (!safePath || safePath.startsWith('..')) return sendError(response, 404, 'Không tìm thấy trang hoặc tệp được yêu cầu.'); const filePath = path.resolve(FRONTEND_DIRECTORY, safePath); if (!filePath.startsWith(`${FRONTEND_DIRECTORY}${path.sep}`)) return sendError(response, 403, 'Không được phép truy cập tệp này.'); try { const content = await fs.readFile(filePath); response.writeHead(200, { 'Content-Type': MIME_TYPES[path.extname(filePath).toLowerCase()] || 'application/octet-stream', 'Cache-Control': 'no-store' }); response.end(request.method === 'HEAD' ? undefined : content); } catch (error) { if (error.code === 'ENOENT') return sendError(response, 404, 'Chưa có bản build React. Hãy chạy npm run build trước khi dùng máy chủ.'); throw error; } }
const server = http.createServer(async (request, response) => { try { const url = new URL(request.url, `http://${request.headers.host || 'localhost'}`); if (url.pathname.startsWith('/api/')) await handleApi(request, response, url); else if (request.method === 'GET' || request.method === 'HEAD') await serveStaticFile(request, response, url); else sendError(response, 405, 'Chỉ hỗ trợ GET hoặc HEAD cho tệp giao diện.'); } catch (error) { console.error(error); sendError(response, 400, error.message || 'Máy chủ không thể xử lý yêu cầu.'); } });
server.listen(PORT, () => console.log(`UET Navigator is running at http://localhost:${PORT}`));
